version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1972
      - 32773:52773
      - 53773
      - 55030:5000
    volumes:
      - ./:/home/irisowner/dev
